/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KasirPackage;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author fhrlzmn
 */
public class Kasir extends javax.swing.JFrame {

    Connection conn;
    Statement state;
    ResultSet rs;
    String sql;

    // Untuk isi tabel
    String idBarang;
    String namaBarang;
    int hargaBarang;
    int jumlahBeli;
    int totalHarga;
    int jumlahBelanja2;
    
    // Untuk uang bayar
    int uangBayar;
    /**
     * Creates new form Kasir
     */
    public Kasir() {
        initComponents();
        ConnectToDatabase Koneksi = new ConnectToDatabase();
        Koneksi.config();
        conn = Koneksi.conn;
        state = Koneksi.state;
        TampilkanBarang();
        AutoCompleteDecorator.decorate(NamaBarangBox);
    }
    
    void uangBayar() {
        GetRupiah rupiah = new GetRupiah();
        String coba;
        if (UangBayarField.getText().isEmpty()) {
            rupiah.Rupiah(uangBayar);
            UangBayarField.setText(rupiah.harga);
        } else {
            coba = UangBayarField.getText().replaceAll("\\.", "");
            int totalUang = Integer.valueOf(coba);
            totalUang += uangBayar;
            rupiah.Rupiah(totalUang);
            UangBayarField.setText(rupiah.harga);
        }
    }
    
    void jumlahkanBelanja() {
        DefaultTableModel model = (DefaultTableModel) TabelPembelian.getModel();
        int baris = model.getRowCount();
        int jumlah;
        int jumlahBelanja = 0;
        
        for (int i = 0; i < baris; i++) {
            jumlah = (int) model.getValueAt(i, 4);
            jumlahBelanja += jumlah;
        }
        
        jumlahBelanja2 = jumlahBelanja;
        GetRupiah cariRupiah = new GetRupiah();
        cariRupiah.Rupiah(jumlahBelanja);
        TotalHarga.setText(cariRupiah.harga);
    }

    public void TampilkanBarang() {
        try {
            sql = "select * from barang";
            rs = state.executeQuery(sql);

            while (rs.next()) {
                NamaBarangBox.addItem(rs.getString("nama_barang"));
            }
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
    }

    public void TampilkanIdDanHarga() {
        try {
            String sql1 = "select id_barang, harga_barang from barang where nama_barang='" + NamaBarangBox.getSelectedItem() + "'";
            rs = state.executeQuery(sql1);
            if (NamaBarangBox.getSelectedIndex() == 0) {
                HargaBarangField.setText("");
            } else {
                while (rs.next()) {
                    //String[] objek = new String[2];
                    idBarang = rs.getString("id_barang");
                    hargaBarang = Integer.valueOf(rs.getString("harga_barang"));
                    namaBarang = (String) NamaBarangBox.getSelectedItem();

                    GetRupiah cariRupiah = new GetRupiah();
                    cariRupiah.Rupiah(hargaBarang);

                    IDBarangField.setText(idBarang);
                    HargaBarangField.setText(cariRupiah.harga);
                }
                rs.close();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KasirPanel = new javax.swing.JPanel();
        Box = new javax.swing.JPanel();
        NamaBarang = new javax.swing.JLabel();
        HargaBarang = new javax.swing.JLabel();
        JumlahBeli = new javax.swing.JLabel();
        JumlahBeliField = new javax.swing.JTextField();
        HargaBarangField = new javax.swing.JTextField();
        NamaBarangBox = new javax.swing.JComboBox<>();
        IDBarang = new javax.swing.JLabel();
        IDBarangField = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        JudulPanel = new javax.swing.JPanel();
        Kasir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TotalHarga = new javax.swing.JTextField();
        UangBayarField = new javax.swing.JTextField();
        KembalianField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tambah100rb = new javax.swing.JButton();
        Tambah50rb = new javax.swing.JButton();
        Tambah20rb = new javax.swing.JButton();
        Tambah10rb = new javax.swing.JButton();
        ClearUangBayar = new javax.swing.JButton();
        BayarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelPembelian = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        ClearAllButton = new javax.swing.JButton();
        KelolaBarangButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KasirApp");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        KasirPanel.setBackground(new java.awt.Color(255, 255, 255));

        Box.setBackground(new java.awt.Color(0, 180, 212));

        NamaBarang.setForeground(new java.awt.Color(255, 255, 255));
        NamaBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NamaBarang.setText("Nama Barang :");
        NamaBarang.setToolTipText("");

        HargaBarang.setForeground(new java.awt.Color(255, 255, 255));
        HargaBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HargaBarang.setText("Harga (Rp) :");
        HargaBarang.setToolTipText("");

        JumlahBeli.setForeground(new java.awt.Color(255, 255, 255));
        JumlahBeli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JumlahBeli.setText("Jumlah Beli :");
        JumlahBeli.setToolTipText("");

        JumlahBeliField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JumlahBeliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBeliFieldActionPerformed(evt);
            }
        });
        JumlahBeliField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JumlahBeliFieldKeyTyped(evt);
            }
        });

        HargaBarangField.setEditable(false);
        HargaBarangField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        HargaBarangField.setToolTipText("");
        HargaBarangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarangFieldActionPerformed(evt);
            }
        });

        NamaBarangBox.setEditable(true);
        NamaBarangBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));
        NamaBarangBox.setSelectedIndex(-1);
        NamaBarangBox.setToolTipText("");
        NamaBarangBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangBoxActionPerformed(evt);
            }
        });

        IDBarang.setForeground(new java.awt.Color(255, 255, 255));
        IDBarang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IDBarang.setText("ID Barang :");
        IDBarang.setToolTipText("");

        IDBarangField.setEditable(false);
        IDBarangField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        IDBarangField.setToolTipText("");
        IDBarangField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDBarangFieldActionPerformed(evt);
            }
        });

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxLayout = new javax.swing.GroupLayout(Box);
        Box.setLayout(BoxLayout);
        BoxLayout.setHorizontalGroup(
            BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BoxLayout.createSequentialGroup()
                        .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HargaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaBarangBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JumlahBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        BoxLayout.setVerticalGroup(
            BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaBarang)
                    .addComponent(NamaBarangBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDBarang)
                    .addComponent(IDBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HargaBarangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahBeliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JumlahBeli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTambah)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        JudulPanel.setBackground(new java.awt.Color(0, 180, 212));
        JudulPanel.setPreferredSize(new java.awt.Dimension(930, 30));

        Kasir.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        Kasir.setForeground(new java.awt.Color(255, 255, 255));
        Kasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kasir.setText("KASIR");

        javax.swing.GroupLayout JudulPanelLayout = new javax.swing.GroupLayout(JudulPanel);
        JudulPanel.setLayout(JudulPanelLayout);
        JudulPanelLayout.setHorizontalGroup(
            JudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JudulPanelLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(Kasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(400, 400, 400))
        );
        JudulPanelLayout.setVerticalGroup(
            JudulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 180, 212));

        TotalHarga.setEditable(false);
        TotalHarga.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        TotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalHarga.setToolTipText("");
        TotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaActionPerformed(evt);
            }
        });

        UangBayarField.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        UangBayarField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        UangBayarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UangBayarFieldActionPerformed(evt);
            }
        });
        UangBayarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UangBayarFieldKeyTyped(evt);
            }
        });

        KembalianField.setEditable(false);
        KembalianField.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        KembalianField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total Belanja");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Uang Bayar (Rp)");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kembalian");

        Tambah100rb.setText("Rp. 100.000,00");
        Tambah100rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah100rbActionPerformed(evt);
            }
        });

        Tambah50rb.setText("Rp. 50.000,00");
        Tambah50rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah50rbActionPerformed(evt);
            }
        });

        Tambah20rb.setText("Rp. 20.000,00");
        Tambah20rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah20rbActionPerformed(evt);
            }
        });

        Tambah10rb.setText("Rp. 10.000,00");
        Tambah10rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah10rbActionPerformed(evt);
            }
        });

        ClearUangBayar.setText("Clear");
        ClearUangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearUangBayarActionPerformed(evt);
            }
        });

        BayarButton.setText("Bayar");
        BayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UangBayarField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalHarga)
                    .addComponent(KembalianField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tambah100rb, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tambah50rb, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tambah20rb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tambah10rb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(ClearUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(UangBayarField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah100rb)
                    .addComponent(Tambah50rb)
                    .addComponent(Tambah20rb)
                    .addComponent(Tambah10rb)
                    .addComponent(ClearUangBayar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KembalianField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga Barang", "Jumlah", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelPembelian.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TabelPembelianAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(TabelPembelian);
        if (TabelPembelian.getColumnModel().getColumnCount() > 0) {
            TabelPembelian.getColumnModel().getColumn(0).setResizable(false);
            TabelPembelian.getColumnModel().getColumn(0).setPreferredWidth(20);
            TabelPembelian.getColumnModel().getColumn(1).setResizable(false);
            TabelPembelian.getColumnModel().getColumn(1).setPreferredWidth(200);
            TabelPembelian.getColumnModel().getColumn(2).setResizable(false);
            TabelPembelian.getColumnModel().getColumn(2).setPreferredWidth(10);
            TabelPembelian.getColumnModel().getColumn(3).setResizable(false);
            TabelPembelian.getColumnModel().getColumn(3).setPreferredWidth(10);
            TabelPembelian.getColumnModel().getColumn(4).setResizable(false);
            TabelPembelian.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jPanel2.setBackground(new java.awt.Color(0, 180, 212));
        jPanel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ketik atau Pilih Nama Barang");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 180, 212));

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        ClearAllButton.setText("Clear All");
        ClearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllButtonActionPerformed(evt);
            }
        });

        KelolaBarangButton.setText("Kelola Barang");
        KelolaBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelolaBarangButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KelolaBarangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KelolaBarangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KasirPanelLayout = new javax.swing.GroupLayout(KasirPanel);
        KasirPanel.setLayout(KasirPanelLayout);
        KasirPanelLayout.setHorizontalGroup(
            KasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JudulPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KasirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(KasirPanelLayout.createSequentialGroup()
                        .addGroup(KasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        KasirPanelLayout.setVerticalGroup(
            KasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KasirPanelLayout.createSequentialGroup()
                .addComponent(JudulPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KasirPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KasirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KasirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JumlahBeliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBeliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahBeliFieldActionPerformed

    private void JumlahBeliFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBeliFieldKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_JumlahBeliFieldKeyTyped

    private void HargaBarangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaBarangFieldActionPerformed

    private void NamaBarangBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangBoxActionPerformed
        TampilkanIdDanHarga();
    }//GEN-LAST:event_NamaBarangBoxActionPerformed

    private void IDBarangFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDBarangFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDBarangFieldActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        if (NamaBarangBox.getSelectedItem() == null || JumlahBeliField.getText().isEmpty() || JumlahBeliField.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Pilih Nama Barang & Jumlah Beli Terlebih Dahulu!");
        } else {
            jumlahBeli = Integer.valueOf(JumlahBeliField.getText());
            totalHarga = this.hargaBarang * this.jumlahBeli;

            GetRupiah cariRupiah = new GetRupiah();

            Object[] row = {this.idBarang, this.namaBarang, this.hargaBarang, this.jumlahBeli, this.totalHarga};

            DefaultTableModel model = (DefaultTableModel) TabelPembelian.getModel();
            model.addRow(row);
            jumlahkanBelanja();
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void TabelPembelianAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TabelPembelianAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelPembelianAncestorAdded

    private void TotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaActionPerformed

    private void UangBayarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UangBayarFieldActionPerformed
       
    }//GEN-LAST:event_UangBayarFieldActionPerformed

    private void Tambah100rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah100rbActionPerformed
        uangBayar += 100000;
        uangBayar();
        uangBayar = 0;
    }//GEN-LAST:event_Tambah100rbActionPerformed

    private void Tambah50rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah50rbActionPerformed
        uangBayar += 50000;
        uangBayar();
        uangBayar = 0;
    }//GEN-LAST:event_Tambah50rbActionPerformed

    private void Tambah20rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah20rbActionPerformed
        uangBayar += 20000;
        uangBayar();
        uangBayar = 0;
    }//GEN-LAST:event_Tambah20rbActionPerformed

    private void Tambah10rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah10rbActionPerformed
        uangBayar += 10000;
        uangBayar();
        uangBayar = 0;
    }//GEN-LAST:event_Tambah10rbActionPerformed

    private void ClearUangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearUangBayarActionPerformed
        uangBayar = 0;
        UangBayarField.setText("");
    }//GEN-LAST:event_ClearUangBayarActionPerformed

    private void UangBayarFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UangBayarFieldKeyTyped

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'){
            UangBayarField.setEditable(true);
        } else {
            UangBayarField.setEditable(false);
        }
    }//GEN-LAST:event_UangBayarFieldKeyTyped

    private void BayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarButtonActionPerformed
        int totalUang2;
        if (UangBayarField.getText().isEmpty()) {
            totalUang2 = 0;
        } else {
            totalUang2 = Integer.valueOf(UangBayarField.getText().replaceAll("\\.", ""));
        }
        int kembalian =  totalUang2 - jumlahBelanja2;
        GetRupiah rupiah = new GetRupiah();
        rupiah.Rupiah(kembalian);
        KembalianField.setText(rupiah.harga);
    }//GEN-LAST:event_BayarButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void ClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllButtonActionPerformed
        NamaBarangBox.setSelectedItem(null);
        JumlahBeliField.setText("");
        TotalHarga.setText("");
        UangBayarField.setText("");
        KembalianField.setText("");
        IDBarangField.setText("");
        HargaBarangField.setText("");
        DefaultTableModel model = (DefaultTableModel) TabelPembelian.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ClearAllButtonActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Menu menu = new Menu();
        LoginPage login = new LoginPage();
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan keluar?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == 0) {
            login.setVisible(true);
            this.setVisible(false);
        } else {
            // tak ada
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void KelolaBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelolaBarangButtonActionPerformed
        KelolaBarang kelola = new KelolaBarang();
        kelola.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KelolaBarangButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BayarButton;
    private javax.swing.JPanel Box;
    private javax.swing.JButton ClearAllButton;
    private javax.swing.JButton ClearUangBayar;
    private javax.swing.JLabel HargaBarang;
    private javax.swing.JTextField HargaBarangField;
    private javax.swing.JLabel IDBarang;
    private javax.swing.JTextField IDBarangField;
    private javax.swing.JPanel JudulPanel;
    private javax.swing.JLabel JumlahBeli;
    private javax.swing.JTextField JumlahBeliField;
    private javax.swing.JLabel Kasir;
    private javax.swing.JPanel KasirPanel;
    private javax.swing.JButton KelolaBarangButton;
    private javax.swing.JTextField KembalianField;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JComboBox<String> NamaBarangBox;
    private javax.swing.JTable TabelPembelian;
    private javax.swing.JButton Tambah100rb;
    private javax.swing.JButton Tambah10rb;
    private javax.swing.JButton Tambah20rb;
    private javax.swing.JButton Tambah50rb;
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JTextField UangBayarField;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
