/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KasirPackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author fhrlzmn
 */
public class RegisterPage extends javax.swing.JFrame {
    // koneksi database
    Connection conn;
    Statement state;
    ResultSet rs;
    String sql;

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        ConnectToDatabase Koneksi = new ConnectToDatabase();
        Koneksi.config();
        conn = Koneksi.conn;
        state = Koneksi.state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        RegisterPanel = new javax.swing.JPanel();
        Box2 = new javax.swing.JPanel();
        RegisterBox = new javax.swing.JPanel();
        RegisterText = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        NamaField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RePasswordField = new javax.swing.JPasswordField();
        RePassword = new javax.swing.JLabel();
        Match = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        ShowPassword = new javax.swing.JCheckBox();
        CancelButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KasirApp");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        RegisterPanel.setBackground(new java.awt.Color(0, 223, 212));

        Box2.setBackground(new java.awt.Color(255, 255, 255));
        Box2.setPreferredSize(new java.awt.Dimension(240, 320));

        RegisterBox.setBackground(new java.awt.Color(0, 180, 212));

        RegisterText.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        RegisterText.setForeground(new java.awt.Color(238, 238, 238));
        RegisterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterText.setText("Register");

        javax.swing.GroupLayout RegisterBoxLayout = new javax.swing.GroupLayout(RegisterBox);
        RegisterBox.setLayout(RegisterBoxLayout);
        RegisterBoxLayout.setHorizontalGroup(
            RegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBoxLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(RegisterText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        RegisterBoxLayout.setVerticalGroup(
            RegisterBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBoxLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(RegisterText)
                .addGap(13, 13, 13))
        );

        Nama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nama.setText("Nama :");

        NamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaFieldActionPerformed(evt);
            }
        });

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Email.setText("Email :");

        Username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Username.setText("Username :");

        Password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Password.setText("Password :");

        RePasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RePasswordFieldKeyReleased(evt);
            }
        });

        RePassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        RePassword.setText("Re-type Password :");

        Match.setText("Password Doesn't Match");
        Match.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MatchKeyReleased(evt);
            }
        });

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Box2Layout = new javax.swing.GroupLayout(Box2);
        Box2.setLayout(Box2Layout);
        Box2Layout.setHorizontalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Box2Layout.createSequentialGroup()
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Box2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nama)
                            .addComponent(Email)
                            .addComponent(Username)
                            .addComponent(Password)
                            .addComponent(RePassword))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Box2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Box2Layout.createSequentialGroup()
                        .addComponent(ShowPassword)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Box2Layout.createSequentialGroup()
                        .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaField)
                            .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RePasswordField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(14, 14, 14))
                    .addGroup(Box2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Match)
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        Box2Layout.setVerticalGroup(
            Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Box2Layout.createSequentialGroup()
                .addComponent(RegisterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Password)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Match)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(CancelButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout RegisterPanelLayout = new javax.swing.GroupLayout(RegisterPanel);
        RegisterPanel.setLayout(RegisterPanelLayout);
        RegisterPanelLayout.setHorizontalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Box2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        RegisterPanelLayout.setVerticalGroup(
            RegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Box2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        String NamaRegister = NamaField.getText();
        String EmailRegister = EmailField.getText();
        String UsernameRegister = UsernameField.getText();
        String PasswordRegister = String.valueOf(PasswordField.getPassword());
        try {
            sql = "INSERT INTO accounts VALUES ('"+NamaRegister+"','"+EmailRegister+"','"+UsernameRegister+"','"+PasswordRegister+"')";
            state.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Registrasi Sukses");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void MatchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatchKeyReleased
        
    }//GEN-LAST:event_MatchKeyReleased

    private void RePasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RePasswordFieldKeyReleased
        String RegisterPassword = new String(PasswordField.getPassword());
        String ReTypePassword = new String(RePasswordField.getPassword());
        
        if (RegisterPassword.equals(ReTypePassword)) {
            Match.setText("Password Match");
        } else if (!RegisterPassword.equals(ReTypePassword)) {
            Match.setText("Password Doesn't Match");
        }
    }//GEN-LAST:event_RePasswordFieldKeyReleased

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if (ShowPassword.isSelected()){
            PasswordField.setEchoChar((char)0);
            RePasswordField.setEchoChar((char)0);
        } else {
            PasswordField.setEchoChar('*');
            RePasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Box2;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel Match;
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RePassword;
    private javax.swing.JPasswordField RePasswordField;
    private javax.swing.JPanel RegisterBox;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RegisterPanel;
    private javax.swing.JLabel RegisterText;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
